services:
  spicedb:
    image: authzed/spicedb:latest
    command: serve-testing
    ports:
      - '50051:50051'
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-v", "--addr", "localhost:50051", "-connect-timeout", "180s"]
