name: publish
on:
  push:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install protobuf tooling
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
